server:
  port: 8080

spring:
    # spring batch   initial database，file in jar
  sql:
    init:
      schema-locations: classpath:org/springframework/batch/core/schema-mysql.sql
      #mode: always
      mode: never
#batch create file path
job:
  data:
    path: D:/demo