server:
  port: 8080
  # thymeleaf  request path
#  servlet:
#    context-path: /security

spring:
  # spring batch   initial database，file in jar
  sql:
    init:
      schema-locations: classpath:org/springframework/batch/core/schema-mysql.sql
      #mode: always
      mode: never
#batch create file path
job:
  data:
    path: D:/demo

minio:
  endpoint: http://xxx.xx.xxx.xx:9000 #Minio服务所在地址
  bucketName: xxxxx #存储桶名称
  accessKey: xxxxxxx #访问的key
  secretKey: xxxxxxx #访问的秘钥

Acount:
  APP_ID: xxx
  APP_SECRET: xxx